print ("My name is Cade")
print ("I like drawing")
print ("I like to play airsoft")
print ("I like to be outdoors")
print ("I like to ride my bike and do wheeliels")
print ("Coding is fun")
print ("The oceain is\n cold today")
print ("I love spider man")
print (12345678910)
print ("I love spider man and the movies.",12345678910)
print ("spider man",end="*")
x=5
y="coding"
print (x)
print (y)
print ("John")